# Generated by Django 5.2.14 on 2026-05-26 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('duration', models.FloatField(verbose_name='时长(秒)')),
                ('sample_rate', models.IntegerField(default=16000, verbose_name='采样率')),
                ('channels', models.IntegerField(default=1, verbose_name='声道数')),
                ('speaker_gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='说话人性别')),
                ('speaker_age', models.CharField(choices=[('child', '儿童(0-12)'), ('teen', '青少年(13-18)'), ('young', '青年(19-35)'), ('middle', '中年(36-55)'), ('senior', '老年(56+)'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='说话人年龄段')),
                ('text_transcript', models.TextField(blank=True, verbose_name='文本转录')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processed', '已处理'), ('assigned', '已分配'), ('annotating', '标注中'), ('reviewing', '审核中'), ('completed', '已完成'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('waveform_data', models.JSONField(blank=True, null=True, verbose_name='波形数据')),
                ('spectrogram_data', models.JSONField(blank=True, null=True, verbose_name='频谱图数据')),
                ('initial_phonemes', models.JSONField(blank=True, null=True, verbose_name='初始音素标注')),
                ('speaker_embedding', models.JSONField(blank=True, null=True, verbose_name='说话人特征向量')),
                ('speaker_embedding_model', models.CharField(blank=True, default='', max_length=50, verbose_name='特征提取模型')),
                ('asr_transcript', models.TextField(blank=True, default='', verbose_name='ASR自动转写文本')),
                ('asr_segments', models.JSONField(blank=True, null=True, verbose_name='ASR分段结果')),
                ('asr_success', models.BooleanField(default=False, verbose_name='ASR是否成功')),
                ('required_annotations', models.IntegerField(default=2, verbose_name='需要的标注数量')),
                ('completed_annotations', models.IntegerField(default=0, verbose_name='已完成的标注数量')),
                ('quality_score', models.FloatField(blank=True, null=True, verbose_name='质量评分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assigned_annotators', models.ManyToManyField(blank=True, related_name='assigned_audio', to=settings.AUTH_USER_MODEL, verbose_name='分配的标注员')),
                ('dialect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialect_audio', to='dialects.dialectregion', verbose_name='方言片区')),
                ('subregion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subregion_audio', to='dialects.dialectsubregion', verbose_name='方言子片区')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audio', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '语音片段',
                'verbose_name_plural': '语音片段',
                'db_table': 'audio_segments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dialect', 'status'], name='audio_segme_dialect_d505ef_idx'), models.Index(fields=['speaker_gender', 'speaker_age'], name='audio_segme_speaker_a5e76f_idx'), models.Index(fields=['created_at'], name='audio_segme_created_f65c04_idx')],
            },
        ),
    ]
