use crate::fsm_dsl::ast::*;
use crate::pipeline::{FpgaFamily, PipelineConfig};

pub struct ConstraintGenerator {
    fsm: FsmDecl,
    pipeline_config: PipelineConfig,
    target: FpgaFamily,
}

impl ConstraintGenerator {
    pub fn new(fsm: FsmDecl, pipeline_config: PipelineConfig, target: FpgaFamily) -> Self {
        ConstraintGenerator { fsm, pipeline_config, target }
    }

    pub fn generate(&self) -> String {
        if self.target.is_intel() {
            self.generate_sdc()
        } else {
            self.generate_xdc()
        }
    }

    fn generate_xdc(&self) -> String {
        let mut out = String::new();

        out.push_str("# Auto-generated by fsm2v compiler\n");
        out.push_str(&format!(
            "# FSM: {} | Clock: {} MHz | Target: {:?}\n\n",
            self.fsm.name.0,
            self.fsm.clock_freq_mhz,
            self.target,
        ));

        let period_ns = 1000.0 / self.fsm.clock_freq_mhz;
        out.push_str(&format!(
            "# Clock constraint\n\
             create_clock -name clk -period {} [get_ports clk]\n\n",
            period_ns
        ));

        match self.fsm.reset_kind {
            ResetKind::Async => {
                out.push_str("# Async reset constraint\n");
                out.push_str("set_false_path -from [get_ports rst_n]\n\n");
            }
            ResetKind::Sync => {
                out.push_str("# Sync reset - no special constraint needed\n\n");
            }
        }

        let (input_delay_ns, output_delay_ns) = self.compute_io_delays_ns();

        out.push_str("# Input delays\n");
        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Input {
                out.push_str(&format!(
                    "set_input_delay -clock clk -max {} [get_ports {}]\n",
                    input_delay_ns,
                    signal.name.0
                ));
                out.push_str(&format!(
                    "set_input_delay -clock clk -min {} [get_ports {}]\n",
                    input_delay_ns * 0.3,
                    signal.name.0
                ));
            }
        }
        out.push_str("\n");

        out.push_str("# Output delays\n");
        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Output {
                out.push_str(&format!(
                    "set_output_delay -clock clk -max {} [get_ports {}]\n",
                    output_delay_ns,
                    signal.name.0
                ));
                out.push_str(&format!(
                    "set_output_delay -clock clk -min {} [get_ports {}]\n",
                    output_delay_ns * 0.3,
                    signal.name.0
                ));
            }
        }
        out.push_str("\n");

        out.push_str("# Clock uncertainty\n");
        let uncertainty_ns = period_ns * 0.05;
        out.push_str(&format!(
            "set_clock_uncertainty -setup {} [get_clocks clk]\n",
            uncertainty_ns
        ));
        out.push_str(&format!(
            "set_clock_uncertainty -hold {} [get_clocks clk]\n",
            uncertainty_ns * 0.5
        ));
        out.push_str("\n");

        if self.pipeline_config.needs_pipeline {
            out.push_str("# Pipeline multi-cycle path constraints\n");
            out.push_str(&format!(
                "# Pipeline depth: {} stages\n",
                self.pipeline_config.num_stages
            ));
            for reg in &self.pipeline_config.stage_registers {
                out.push_str(&format!(
                    "set_multicycle_path {} -to [get_cells -hierarchical -filter {{NAME =~ *{}*}}] -setup\n",
                    reg.stage, reg.name
                ));
                out.push_str(&format!(
                    "set_multicycle_path {} -to [get_cells -hierarchical -filter {{NAME =~ *{}*}}] -hold\n",
                    reg.stage, reg.name
                ));
            }
            out.push_str("\n");
        }

        out.push_str("# FSM state encoding attributes\n");
        out.push_str(&format!(
            "set_property FSM_ENCODING {} [get_cells -hierarchical -filter {{NAME =~ */current_state*}}]\n",
            match self.fsm.encoding {
                StateEncoding::Binary => "AUTO",
                StateEncoding::OneHot => "ONE_HOT",
                StateEncoding::Gray => "GRAY",
                StateEncoding::User => "USER",
            }
        ));
        out.push_str(
            "set_property SAFE_IMPLEMENTATION SAFE [get_cells -hierarchical -filter {NAME =~ */current_state*}]\n"
        );

        out
    }

    fn generate_sdc(&self) -> String {
        let mut out = String::new();

        out.push_str("# Auto-generated by fsm2v compiler (Intel FPGA SDC format)\n");
        out.push_str(&format!(
            "# FSM: {} | Clock: {} MHz | Target: {:?}\n\n",
            self.fsm.name.0,
            self.fsm.clock_freq_mhz,
            self.target,
        ));

        let period_ns = 1000.0 / self.fsm.clock_freq_mhz;
        out.push_str(&format!(
            "# Clock constraint\n\
             create_clock -name clk -period {} [get_ports {{clk}}]\n\n",
            period_ns
        ));

        match self.fsm.reset_kind {
            ResetKind::Async => {
                out.push_str("# Async reset constraint\n");
                out.push_str("set_false_path -from [get_ports {rst_n}]\n\n");
            }
            ResetKind::Sync => {
                out.push_str("# Sync reset - no special constraint needed\n\n");
            }
        }

        let (input_delay_ns, output_delay_ns) = self.compute_io_delays_ns();

        out.push_str("# Input delays\n");
        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Input {
                out.push_str(&format!(
                    "set_input_delay -max -clock clk {} [get_ports {{{}}}]\n",
                    input_delay_ns,
                    signal.name.0
                ));
                out.push_str(&format!(
                    "set_input_delay -min -clock clk {} [get_ports {{{}}}]\n",
                    input_delay_ns * 0.3,
                    signal.name.0
                ));
            }
        }
        out.push_str("\n");

        out.push_str("# Output delays\n");
        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Output {
                out.push_str(&format!(
                    "set_output_delay -max -clock clk {} [get_ports {{{}}}]\n",
                    output_delay_ns,
                    signal.name.0
                ));
                out.push_str(&format!(
                    "set_output_delay -min -clock clk {} [get_ports {{{}}}]\n",
                    output_delay_ns * 0.3,
                    signal.name.0
                ));
            }
        }
        out.push_str("\n");

        out.push_str("# Clock uncertainty\n");
        let _uncertainty_ns = period_ns * 0.05;
        out.push_str(&format!(
            "derive_clock_uncertainty\n"
        ));
        out.push_str("\n");

        if self.pipeline_config.needs_pipeline {
            out.push_str("# Pipeline multi-cycle path constraints\n");
            for reg in &self.pipeline_config.stage_registers {
                out.push_str(&format!(
                    "set_multicycle_path -to [get_registers *{}*] -setup {}\n",
                    reg.name, reg.stage
                ));
                out.push_str(&format!(
                    "set_multicycle_path -to [get_registers *{}*] -hold {}\n",
                    reg.name, reg.stage
                ));
            }
            out.push_str("\n");
        }

        out
    }

    fn compute_io_delays_ns(&self) -> (f64, f64) {
        let period_ns = 1000.0 / self.fsm.clock_freq_mhz;

        let (input_frac, output_frac) = match self.target {
            FpgaFamily::Xilinx7Series => (0.40, 0.40),
            FpgaFamily::XilinxUltraScale => (0.35, 0.35),
            FpgaFamily::XilinxUltraScalePlus => (0.30, 0.30),
            FpgaFamily::IntelCyclone10 => (0.45, 0.45),
            FpgaFamily::IntelStratix10 => (0.35, 0.35),
            FpgaFamily::IntelAgilex => (0.30, 0.30),
            FpgaFamily::Generic => (0.40, 0.40),
        };

        let max_external_delay_ns = 4.0;

        let input_delay = (period_ns * input_frac).min(max_external_delay_ns);
        let output_delay = (period_ns * output_frac).min(max_external_delay_ns);

        (input_delay, output_delay)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_fsm() -> FsmDecl {
        FsmDecl {
            name: Ident("test_fsm".into()),
            clock_freq_mhz: 100.0,
            reset_kind: ResetKind::Async,
            encoding: StateEncoding::Binary,
            states: vec![
                StateDecl { name: Ident("IDLE".into()), is_initial: true, encoding: None },
            ],
            transitions: vec![],
            signals: vec![
                SignalDecl { name: Ident("data_in".into()), width: 8, kind: SignalKind::Input },
                SignalDecl { name: Ident("data_out".into()), width: 8, kind: SignalKind::Output },
            ],
            parameters: vec![],
        }
    }

    #[test]
    fn test_xdc_generation() {
        let fsm = make_test_fsm();
        let config = PipelineConfig {
            num_stages: 1,
            stage_registers: vec![],
            target_period_ps: 10000,
            needs_pipeline: false,
            estimated_delay_ps: 2000,
        };
        let gen = ConstraintGenerator::new(fsm, config, FpgaFamily::Xilinx7Series);
        let xdc = gen.generate();
        assert!(xdc.contains("create_clock"));
        assert!(xdc.contains("set_false_path"));
        assert!(xdc.contains("set_input_delay"));
        assert!(xdc.contains("set_output_delay"));
        assert!(xdc.contains("set_clock_uncertainty"));
        assert!(!xdc.contains("get_registers"), "XDC should use get_cells, not get_registers");
    }

    #[test]
    fn test_sdc_generation() {
        let fsm = make_test_fsm();
        let config = PipelineConfig {
            num_stages: 1,
            stage_registers: vec![],
            target_period_ps: 10000,
            needs_pipeline: false,
            estimated_delay_ps: 2000,
        };
        let gen = ConstraintGenerator::new(fsm, config, FpgaFamily::IntelStratix10);
        let sdc = gen.generate();
        assert!(sdc.contains("create_clock"));
        assert!(sdc.contains("set_false_path"));
        assert!(sdc.contains("get_ports {clk}"), "SDC should use {{clk}} syntax");
    }

    #[test]
    fn test_xdc_pipeline_uses_get_cells() {
        let fsm = make_test_fsm();
        let config = PipelineConfig {
            num_stages: 2,
            stage_registers: vec![crate::pipeline::StageRegister {
                name: "cnt_pipe1".into(),
                width: 8,
                stage: 1,
            }],
            target_period_ps: 10000,
            needs_pipeline: true,
            estimated_delay_ps: 5000,
        };
        let gen = ConstraintGenerator::new(fsm, config, FpgaFamily::Xilinx7Series);
        let xdc = gen.generate();
        assert!(xdc.contains("get_cells"), "XDC pipeline constraints must use get_cells");
        assert!(!xdc.contains("get_registers"), "XDC must NOT use get_registers");
    }

    #[test]
    fn test_io_delay_bounded() {
        let fsm = make_test_fsm();
        let config = PipelineConfig {
            num_stages: 1,
            stage_registers: vec![],
            target_period_ps: 10000,
            needs_pipeline: false,
            estimated_delay_ps: 2000,
        };
        let gen = ConstraintGenerator::new(fsm, config, FpgaFamily::Xilinx7Series);
        let (input_delay, output_delay) = gen.compute_io_delays_ns();
        assert!(input_delay <= 4.0, "input delay should be bounded by max external delay");
        assert!(output_delay <= 4.0, "output delay should be bounded by max external delay");
    }
}
