// Auto-generated by fsm2v compiler
// FSM: traffic_light
// Clock frequency: 100 MHz
// Target: Xilinx7Series
// Pipeline stages: 1
// State encoding: Binary

module traffic_light (
    input wire clk,
    input wire rst_n
,
    input wire sensor,
    input wire emergency,
    output reg [1:0] light
);

    localparam STATE_WIDTH = 2;

    localparam [STATE_WIDTH-1:0] IDLE = 2'd0;
    localparam [STATE_WIDTH-1:0] GREEN = 2'd1;
    localparam [STATE_WIDTH-1:0] YELLOW = 2'd2;
    localparam [STATE_WIDTH-1:0] RED = 2'd3;

    reg [STATE_WIDTH-1:0] current_state;
    reg [STATE_WIDTH-1:0] next_state;

    reg [7:0] counter;
    reg [7:0] counter_next;

    always @(*) begin
        next_state = current_state;
        counter_next = counter;
        light = 2'd0;

        case (current_state)
            IDLE: begin
                if ((sensor == 1)) begin
                    next_state = GREEN;
                    light = 1;
                    counter_next = 0;
                end else if ((sensor == 0)) begin
                    next_state = IDLE;
                end else begin
                    next_state = IDLE;
                end
            end
            GREEN: begin
                if ((counter >= 100)) begin
                    next_state = YELLOW;
                    light = 2;
                    counter_next = 0;
                end else if ((counter < 100)) begin
                    next_state = GREEN;
                    counter_next = (counter + 1);
                end else if ((emergency == 1)) begin
                    next_state = RED;
                    light = 3;
                    counter_next = 0;
                end else begin
                    next_state = GREEN;
                end
            end
            YELLOW: begin
                if (((counter >= 30) || (emergency == 1))) begin
                    next_state = RED;
                    light = 3;
                    counter_next = 0;
                end else if ((counter < 30)) begin
                    next_state = YELLOW;
                    counter_next = (counter + 1);
                end else begin
                    next_state = YELLOW;
                end
            end
            RED: begin
                if ((counter >= 80)) begin
                    next_state = GREEN;
                    light = 1;
                    counter_next = 0;
                end else if ((counter < 80)) begin
                    next_state = RED;
                    counter_next = (counter + 1);
                end else if ((emergency == 1)) begin
                    next_state = RED;
                end else begin
                    next_state = RED;
                end
            end
        endcase
    end

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            current_state <= IDLE;
            light <= 2'd0;
            counter <= 8'd0;
        end else begin
            current_state <= next_state;
            counter <= counter_next;
        end
    end

endmodule
