use crate::fsm_dsl::ast::*;
use crate::pipeline::{FpgaFamily, PipelineConfig};

pub struct VerilogGenerator {
    fsm: FsmDecl,
    pipeline_config: PipelineConfig,
    target: FpgaFamily,
}

impl VerilogGenerator {
    pub fn new(fsm: FsmDecl, pipeline_config: PipelineConfig, target: FpgaFamily) -> Self {
        VerilogGenerator { fsm, pipeline_config, target }
    }

    pub fn generate(&self) -> String {
        let mut out = String::new();

        self.emit_header(&mut out);
        self.emit_module_declaration(&mut out);
        self.emit_state_encoding(&mut out);
        self.emit_signal_declarations(&mut out);
        self.emit_pipeline_registers(&mut out);

        if self.pipeline_config.num_stages > 1 {
            self.emit_pipelined_logic(&mut out);
        } else {
            self.emit_combinational_logic(&mut out);
            self.emit_sequential_logic(&mut out);
        }

        self.emit_endmodule(&mut out);

        out
    }

    fn emit_header(&self, out: &mut String) {
        out.push_str(&format!(
            "// Auto-generated by fsm2v compiler\n\
             // FSM: {}\n\
             // Clock frequency: {} MHz\n\
             // Target: {:?}\n\
             // Pipeline stages: {}\n\
             // State encoding: {:?}\n\n",
            self.fsm.name.0,
            self.fsm.clock_freq_mhz,
            self.target,
            self.pipeline_config.num_stages,
            self.fsm.encoding,
        ));
    }

    fn emit_module_declaration(&self, out: &mut String) {
        out.push_str(&format!("module {} (\n", self.fsm.name.0));

        let indent = "    ";
        out.push_str(&format!("{}input wire clk,\n", indent));

        match self.fsm.reset_kind {
            ResetKind::Sync => out.push_str(&format!("{}input wire rst_n\n", indent)),
            ResetKind::Async => out.push_str(&format!("{}input wire rst_n\n", indent)),
        }

        for signal in &self.fsm.signals {
            match signal.kind {
                SignalKind::Input => {
                    if signal.width == 1 {
                        out.push_str(&format!(",\n{}input wire {}", indent, signal.name.0));
                    } else {
                        out.push_str(&format!(
                            ",\n{}input wire [{}:0] {}",
                            indent,
                            signal.width - 1,
                            signal.name.0
                        ));
                    }
                }
                SignalKind::Output => {
                    if signal.width == 1 {
                        out.push_str(&format!(",\n{}output reg {}", indent, signal.name.0));
                    } else {
                        out.push_str(&format!(
                            ",\n{}output reg [{}:0] {}",
                            indent,
                            signal.width - 1,
                            signal.name.0
                        ));
                    }
                }
                SignalKind::Register => {}
            }
        }

        out.push_str("\n);\n\n");
    }

    fn emit_state_encoding(&self, out: &mut String) {
        let width = self.fsm.state_width();

        match self.fsm.encoding {
            StateEncoding::Binary => {
                out.push_str(&format!(
                    "    localparam STATE_WIDTH = {};\n\n",
                    width
                ));
                for (i, state) in self.fsm.states.iter().enumerate() {
                    out.push_str(&format!(
                        "    localparam [STATE_WIDTH-1:0] {} = {}'d{};\n",
                        state.name.0, width, i
                    ));
                }
            }
            StateEncoding::OneHot => {
                let n = self.fsm.num_states();
                out.push_str(&format!(
                    "    localparam STATE_WIDTH = {};\n\n",
                    n
                ));
                for (i, state) in self.fsm.states.iter().enumerate() {
                    let zeros_before = "0".repeat(i);
                    let one = if i < n { "1" } else { "" };
                    let zeros_after = "0".repeat(n.saturating_sub(i + 1));
                    out.push_str(&format!(
                        "    localparam [STATE_WIDTH-1:0] {} = {}'b{}{}{};\n",
                        state.name.0,
                        n,
                        zeros_before,
                        one,
                        zeros_after,
                    ));
                }
            }
            StateEncoding::Gray => {
                out.push_str(&format!(
                    "    localparam STATE_WIDTH = {};\n\n",
                    width
                ));
                for (i, state) in self.fsm.states.iter().enumerate() {
                    let gray = i ^ (i >> 1);
                    out.push_str(&format!(
                        "    localparam [STATE_WIDTH-1:0] {} = {}'d{};\n",
                        state.name.0, width, gray
                    ));
                }
            }
            StateEncoding::User => {
                out.push_str(&format!(
                    "    localparam STATE_WIDTH = {};\n\n",
                    width
                ));
                for state in &self.fsm.states {
                    let val = state.encoding.unwrap_or(0);
                    out.push_str(&format!(
                        "    localparam [STATE_WIDTH-1:0] {} = {}'d{};\n",
                        state.name.0, width, val
                    ));
                }
            }
        }
        out.push_str("\n");
    }

    fn emit_signal_declarations(&self, out: &mut String) {
        out.push_str("    reg [STATE_WIDTH-1:0] current_state;\n");
        out.push_str("    reg [STATE_WIDTH-1:0] next_state;\n\n");

        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Register {
                if signal.width == 1 {
                    out.push_str(&format!("    reg {};\n", signal.name.0));
                    out.push_str(&format!("    reg {}_next;\n", signal.name.0));
                } else {
                    out.push_str(&format!(
                        "    reg [{}:0] {};\n",
                        signal.width - 1,
                        signal.name.0
                    ));
                    out.push_str(&format!(
                        "    reg [{}:0] {}_next;\n",
                        signal.width - 1,
                        signal.name.0
                    ));
                }
            }
        }
        out.push_str("\n");
    }

    fn emit_pipeline_registers(&self, out: &mut String) {
        if self.pipeline_config.num_stages <= 1 {
            return;
        }

        for reg in &self.pipeline_config.stage_registers {
            if reg.width == 1 {
                out.push_str(&format!("    reg {};\n", reg.name));
            } else {
                out.push_str(&format!(
                    "    reg [{}:0] {};\n",
                    reg.width - 1,
                    reg.name
                ));
            }
        }
        out.push_str("\n");
    }

    fn emit_combinational_logic(&self, out: &mut String) {
        out.push_str("    always @(*) begin\n");
        out.push_str("        next_state = current_state;\n");

        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Register {
                if signal.width == 1 {
                    out.push_str(&format!("        {}_next = {};\n", signal.name.0, signal.name.0));
                } else {
                    out.push_str(&format!("        {}_next = {};\n", signal.name.0, signal.name.0));
                }
            }
        }

        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Output {
                if signal.width == 1 {
                    out.push_str(&format!("        {} = 1'b0;\n", signal.name.0));
                } else {
                    out.push_str(&format!(
                        "        {} = {}'d0;\n",
                        signal.name.0,
                        signal.width
                    ));
                }
            }
        }

        out.push_str("\n");
        out.push_str("        case (current_state)\n");

        for state in &self.fsm.states {
            out.push_str(&format!("            {}: begin\n", state.name.0));
            let state_transitions: Vec<&Transition> = self.fsm
                .transitions
                .iter()
                .filter(|t| t.from_state == state.name)
                .collect();

            let conditional: Vec<&&Transition> = state_transitions.iter().filter(|t| t.condition.is_some()).collect();
            let default_trans: Vec<&&Transition> = state_transitions.iter().filter(|t| t.condition.is_none()).collect();

            if !conditional.is_empty() {
                for (i, t) in conditional.iter().enumerate() {
                    let cond = t.condition.as_ref().unwrap();
                    if i == 0 {
                        out.push_str(&format!("                if ({}) begin\n", Self::emit_expr(cond)));
                    } else {
                        out.push_str(&format!("                end else if ({}) begin\n", Self::emit_expr(cond)));
                    }
                    out.push_str(&format!("                    next_state = {};\n", t.to_state.0));
                    for a in &t.actions {
                        out.push_str(&format!("                    {}\n", self.emit_action(a)));
                    }
                }

                if let Some(dt) = default_trans.first() {
                    out.push_str("                end else begin\n");
                    out.push_str(&format!("                    next_state = {};\n", dt.to_state.0));
                    for a in &dt.actions {
                        out.push_str(&format!("                    {}\n", self.emit_action(a)));
                    }
                    out.push_str("                end\n");
                } else {
                    out.push_str("                end else begin\n");
                    out.push_str("                    next_state = current_state;\n");
                    out.push_str("                end\n");
                }
            } else if let Some(dt) = default_trans.first() {
                out.push_str("                begin\n");
                out.push_str(&format!("                    next_state = {};\n", dt.to_state.0));
                for a in &dt.actions {
                    out.push_str(&format!("                    {}\n", self.emit_action(a)));
                }
                out.push_str("                end\n");
            } else {
                out.push_str("                begin\n");
                out.push_str("                    next_state = current_state;\n");
                out.push_str("                end\n");
            }

            out.push_str("            end\n");
        }

        out.push_str("        endcase\n");
        out.push_str("    end\n\n");
    }

    fn emit_sequential_logic(&self, out: &mut String) {
        match self.fsm.reset_kind {
            ResetKind::Async => {
                out.push_str("    always @(posedge clk or negedge rst_n) begin\n");
                out.push_str("        if (!rst_n) begin\n");
            }
            ResetKind::Sync => {
                out.push_str("    always @(posedge clk) begin\n");
                out.push_str("        if (!rst_n) begin\n");
            }
        }

        let initial = self.fsm.initial_state().map(|s| s.name.0.as_str()).unwrap_or("IDLE");
        out.push_str(&format!("            current_state <= {};\n", initial));

        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Register {
                if signal.width == 1 {
                    out.push_str(&format!("            {} <= 1'b0;\n", signal.name.0));
                } else {
                    out.push_str(&format!(
                        "            {} <= {}'d0;\n",
                        signal.name.0,
                        signal.width
                    ));
                }
            } else if signal.kind == SignalKind::Output {
                if signal.width == 1 {
                    out.push_str(&format!("            {} <= 1'b0;\n", signal.name.0));
                } else {
                    out.push_str(&format!(
                        "            {} <= {}'d0;\n",
                        signal.name.0,
                        signal.width
                    ));
                }
            }
        }

        out.push_str("        end else begin\n");
        out.push_str("            current_state <= next_state;\n");

        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Register {
                out.push_str(&format!(
                    "            {} <= {}_next;\n",
                    signal.name.0,
                    signal.name.0
                ));
            }
        }

        out.push_str("        end\n");
        out.push_str("    end\n\n");
    }

    fn emit_pipelined_logic(&self, out: &mut String) {
        let num_stages = self.pipeline_config.num_stages;

        out.push_str("    // Pipeline Stage 0: State transition computation\n");
        self.emit_combinational_logic(out);

        for stage in 1..num_stages {
            out.push_str(&format!(
                "    // Pipeline Stage {}: Register\n",
                stage
            ));

            match self.fsm.reset_kind {
                ResetKind::Async => {
                    out.push_str("    always @(posedge clk or negedge rst_n) begin\n");
                    out.push_str("        if (!rst_n) begin\n");
                }
                ResetKind::Sync => {
                    out.push_str("    always @(posedge clk) begin\n");
                    out.push_str("        if (!rst_n) begin\n");
                }
            }

            if stage == 1 {
                let initial = self.fsm.initial_state().map(|s| s.name.0.as_str()).unwrap_or("IDLE");
                out.push_str(&format!(
                    "            current_state <= {};\n",
                    initial
                ));
            }

            for reg in &self.pipeline_config.stage_registers {
                if reg.stage == stage {
                    if reg.width == 1 {
                        out.push_str(&format!(
                            "            {} <= 1'b0;\n",
                            reg.name
                        ));
                    } else {
                        out.push_str(&format!(
                            "            {} <= {}'d0;\n",
                            reg.name,
                            reg.width
                        ));
                    }
                }
            }

            out.push_str("        end else begin\n");

            if stage == 1 {
                out.push_str("            current_state <= next_state;\n");
            }

            for reg in &self.pipeline_config.stage_registers {
                if reg.stage == stage {
                    out.push_str(&format!(
                        "            {} <= {};\n",
                        reg.name,
                        self.pipeline_input_name(&reg.name, stage)
                    ));
                }
            }

            out.push_str("        end\n");
            out.push_str("    end\n\n");
        }

        out.push_str("    // Final output assignment from pipeline\n");
        for signal in &self.fsm.signals {
            if signal.kind == SignalKind::Output || signal.kind == SignalKind::Register {
                let last_pipe = format!("{}_pipe{}", signal.name.0, num_stages - 1);
                out.push_str(&format!(
                    "    assign {} = {};\n",
                    signal.name.0,
                    last_pipe
                ));
            }
        }
        out.push_str("\n");
    }

    fn pipeline_input_name(&self, reg_name: &str, stage: u32) -> String {
        if stage == 1 {
            if reg_name.ends_with("_pipe1") {
                let base = &reg_name[..reg_name.len() - 6];
                format!("{}_next", base)
            } else {
                format!("{}_next", reg_name)
            }
        } else {
            reg_name.replace(
                &format!("_pipe{}", stage),
                &format!("_pipe{}", stage - 1),
            )
        }
    }

    fn emit_endmodule(&self, out: &mut String) {
        out.push_str("endmodule\n");
    }

    fn emit_expr(expr: &Expr) -> String {
        match expr {
            Expr::Literal(n) => format!("{}", n),
            Expr::Var(id) => id.0.clone(),
            Expr::BinOp(op, lhs, rhs) => {
                let op_str = match op {
                    BinOp::Add => "+",
                    BinOp::Sub => "-",
                    BinOp::Mul => "*",
                    BinOp::And => "&",
                    BinOp::Or => "|",
                    BinOp::Xor => "^",
                    BinOp::Shl => "<<",
                    BinOp::Shr => ">>",
                    BinOp::Eq => "==",
                    BinOp::Ne => "!=",
                    BinOp::Lt => "<",
                    BinOp::Le => "<=",
                    BinOp::Gt => ">",
                    BinOp::Ge => ">=",
                    BinOp::LogicAnd => "&&",
                    BinOp::LogicOr => "||",
                };
                format!("({} {} {})", Self::emit_expr(lhs), op_str, Self::emit_expr(rhs))
            }
            Expr::UnaryOp(op, inner) => {
                let op_str = match op {
                    UnaryOp::Not => "~",
                    UnaryOp::Neg => "-",
                };
                format!("({}{})", op_str, Self::emit_expr(inner))
            }
            Expr::Ternary(cond, then_, else_) => {
                format!(
                    "(({}) ? ({}) : ({}))",
                    Self::emit_expr(cond),
                    Self::emit_expr(then_),
                    Self::emit_expr(else_)
                )
            }
            Expr::Concat(exprs) => {
                let parts: Vec<String> = exprs.iter().map(Self::emit_expr).collect();
                format!("{{{}}}", parts.join(", "))
            }
            Expr::BitSlice(inner, high, low) => {
                format!("{}[{}:{}]", Self::emit_expr(inner), high, low)
            }
        }
    }

    fn emit_action(&self, action: &Action) -> String {
        match action {
            Action::Assign { target, value } => {
                let is_reg = self.fsm.signals.iter()
                    .any(|s| s.name.0 == target.0 && s.kind == SignalKind::Register);
                if is_reg {
                    format!("{}_next = {};", target.0, Self::emit_expr(value))
                } else {
                    format!("{} = {};", target.0, Self::emit_expr(value))
                }
            }
            Action::Output { signal, value } => {
                format!("{} = {};", signal.0, Self::emit_expr(value))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pipeline::PipelineConfig;

    fn make_simple_fsm() -> FsmDecl {
        FsmDecl {
            name: Ident("test_fsm".into()),
            clock_freq_mhz: 100.0,
            reset_kind: ResetKind::Sync,
            encoding: StateEncoding::Binary,
            states: vec![
                StateDecl { name: Ident("IDLE".into()), is_initial: true, encoding: None },
                StateDecl { name: Ident("RUN".into()), is_initial: false, encoding: None },
            ],
            transitions: vec![
                Transition {
                    from_state: Ident("IDLE".into()),
                    condition: Some(Expr::Var(Ident("start".into()))),
                    to_state: Ident("RUN".into()),
                    actions: vec![Action::Assign {
                        target: Ident("counter".into()),
                        value: Expr::Literal(0),
                    }],
                },
                Transition {
                    from_state: Ident("IDLE".into()),
                    condition: None,
                    to_state: Ident("IDLE".into()),
                    actions: vec![],
                },
                Transition {
                    from_state: Ident("RUN".into()),
                    condition: Some(Expr::BinOp(
                        BinOp::Ge,
                        Box::new(Expr::Var(Ident("counter".into()))),
                        Box::new(Expr::Literal(100)),
                    )),
                    to_state: Ident("IDLE".into()),
                    actions: vec![Action::Output {
                        signal: Ident("done".into()),
                        value: Expr::Literal(1),
                    }],
                },
                Transition {
                    from_state: Ident("RUN".into()),
                    condition: None,
                    to_state: Ident("RUN".into()),
                    actions: vec![Action::Assign {
                        target: Ident("counter".into()),
                        value: Expr::BinOp(
                            BinOp::Add,
                            Box::new(Expr::Var(Ident("counter".into()))),
                            Box::new(Expr::Literal(1)),
                        ),
                    }],
                },
            ],
            signals: vec![
                SignalDecl { name: Ident("start".into()), width: 1, kind: SignalKind::Input },
                SignalDecl { name: Ident("done".into()), width: 1, kind: SignalKind::Output },
                SignalDecl { name: Ident("counter".into()), width: 8, kind: SignalKind::Register },
            ],
            parameters: vec![],
        }
    }

    #[test]
    fn test_verilog_generation() {
        let fsm = make_simple_fsm();
        let config = PipelineConfig {
            num_stages: 1,
            stage_registers: vec![],
            target_period_ps: 10000,
            needs_pipeline: false,
            estimated_delay_ps: 2000,
        };
        let gen = VerilogGenerator::new(fsm, config, FpgaFamily::Xilinx7Series);
        let verilog = gen.generate();
        assert!(verilog.contains("module test_fsm"));
        assert!(verilog.contains("always @(posedge clk)"));
        assert!(verilog.contains("IDLE"));
        assert!(verilog.contains("RUN"));
        assert!(verilog.contains("counter_next"));
        assert!(!verilog.contains("counter <= counter;"), "no self-assignment for registers");
    }

    #[test]
    fn test_no_self_assignment_in_sequential() {
        let fsm = make_simple_fsm();
        let config = PipelineConfig {
            num_stages: 1,
            stage_registers: vec![],
            target_period_ps: 10000,
            needs_pipeline: false,
            estimated_delay_ps: 2000,
        };
        let gen = VerilogGenerator::new(fsm, config, FpgaFamily::Xilinx7Series);
        let verilog = gen.generate();

        for line in verilog.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("counter <=") && !trimmed.contains("counter_next") && !trimmed.contains("1'b0") && !trimmed.contains("'d0") {
                panic!("Found illegal self-assignment: {}", trimmed);
            }
        }
    }
}
