#include "phylogeny\NexusExporter.h"
#include "core/Utils.h"
#include <algorithm>
#include <sstream>
#include <iomanip>
#include <sys/stat.h>
#include <filesystem>

namespace Fossil3D {

NexusExporter::NexusExporter() {
}

NexusExporter::~NexusExporter() {
}

void NexusExporter::setOptions(const NexusExportOptions& options) {
    m_options = options;
}

std::string NexusExporter::formatContinuousValue(double value, int precision) {
    if (value == m_options.missingValue || std::isnan(value) || std::isinf(value)) {
        return std::string(1, m_options.missingCharacter);
    }
    std::ostringstream oss;
    oss << std::fixed << std::setprecision(precision) << value;
    return oss.str();
}

std::string NexusExporter::formatDiscreteValue(double value, double min, double max) {
    if (value == m_options.missingValue || std::isnan(value) || std::isinf(value)) {
        return std::string(1, m_options.missingCharacter);
    }

    double range = max - min;
    if (range < 1e-10) {
        return "0";
    }

    double normalized = (value - min) / range;
    int state = static_cast<int>(normalized * m_options.numStates);
    state = std::max(0, std::min(state, m_options.numStates - 1));

    return std::to_string(state);
}

std::string NexusExporter::truncateTaxonName(const std::string& name, int maxLength) {
    if (static_cast<int>(name.length()) <= maxLength) {
        return name;
    }
    return name.substr(0, maxLength);
}

std::string NexusExporter::escapeNexusString(const std::string& input) {
    std::string result = input;
    std::replace(result.begin(), result.end(), ' ', '_');
    std::replace(result.begin(), result.end(), ':', '_');
    std::replace(result.begin(), result.end(), '(', '[');
    std::replace(result.begin(), result.end(), ')', ']');
    return result;
}

double NexusExporter::getFeatureMin(const std::vector<PhylogeneticDataset>& datasets,
                                     const std::string& featureName) {
    double minVal = 1e100;
    for (const auto& ds : datasets) {
        auto it = ds.featureMap.find(featureName);
        if (it != ds.featureMap.end()) {
            if (it->second != m_options.missingValue && !std::isnan(it->second)) {
                minVal = std::min(minVal, it->second);
            }
        }
    }
    return minVal < 1e99 ? minVal : 0.0;
}

double NexusExporter::getFeatureMax(const std::vector<PhylogeneticDataset>& datasets,
                                     const std::string& featureName) {
    double maxVal = -1e100;
    for (const auto& ds : datasets) {
        auto it = ds.featureMap.find(featureName);
        if (it != ds.featureMap.end()) {
            if (it->second != m_options.missingValue && !std::isnan(it->second)) {
                maxVal = std::max(maxVal, it->second);
            }
        }
    }
    return maxVal > -1e99 ? maxVal : 1.0;
}

std::vector<std::string> NexusExporter::getCommonFeatures(const std::vector<PhylogeneticDataset>& datasets) {
    if (datasets.empty()) return {};

    std::map<std::string, int> featureCount;
    for (const auto& ds : datasets) {
        for (const auto& f : ds.features) {
            featureCount[f.name]++;
        }
    }

    std::vector<std::string> common;
    for (const auto& pair : featureCount) {
        if (pair.second == static_cast<int>(datasets.size())) {
            common.push_back(pair.first);
        }
    }

    std::sort(common.begin(), common.end());
    return common;
}

std::string NexusExporter::generateHeader(const std::vector<PhylogeneticDataset>& datasets) {
    std::ostringstream oss;
    oss << "#NEXUS" << std::endl;
    oss << "[" << std::endl;
    oss << "  Generated by Fossil3D Reconstruction Software" << std::endl;
    oss << "  Date: " << __DATE__ << " " << __TIME__ << std::endl;
    oss << "  Number of taxa: " << datasets.size() << std::endl;
    oss << "  Number of characters: " << getCommonFeatures(datasets).size() << std::endl;
    if (!m_options.customNotes.empty()) {
        oss << "  Notes: " << m_options.customNotes << std::endl;
    }
    oss << "]" << std::endl << std::endl;
    return oss.str();
}

std::string NexusExporter::generateTaxaBlock(const std::vector<PhylogeneticDataset>& datasets) {
    std::ostringstream oss;
    oss << "BEGIN TAXA;" << std::endl;
    oss << "  DIMENSIONS NTAX=" << datasets.size() << ";" << std::endl;
    oss << "  TAXLABELS" << std::endl;
    for (const auto& ds : datasets) {
        std::string taxonName = escapeNexusString(truncateTaxonName(ds.taxonName));
        oss << "    " << taxonName << " [specimen: " << ds.specimenID << "]" << std::endl;
    }
    oss << "  ;" << std::endl;
    oss << "END; [TAXA]" << std::endl << std::endl;
    return oss.str();
}

std::string NexusExporter::generateCharactersBlock(const std::vector<PhylogeneticDataset>& datasets,
                                                     const std::vector<std::string>& selectedFeatures) {
    auto features = selectedFeatures.empty() ? getCommonFeatures(datasets) : selectedFeatures;

    std::ostringstream oss;
    oss << "BEGIN CHARACTERS;" << std::endl;
    oss << "  DIMENSIONS NCHAR=" << features.size() << ";" << std::endl;
    oss << "  FORMAT DATATYPE=";

    if (m_options.dataType == NexusDataType::CONTINUOUS) {
        oss << "CONTINUOUS MISSING=" << m_options.missingCharacter;
    } else if (m_options.dataType == NexusDataType::STANDARD) {
        oss << "STANDARD MISSING=" << m_options.missingCharacter 
            << " GAP=" << m_options.gapCharacter
            << " SYMBOLS=\"0123456789\"";
    } else if (m_options.dataType == NexusDataType::DNA) {
        oss << "DNA MISSING=" << m_options.missingCharacter 
            << " GAP=" << m_options.gapCharacter;
    } else if (m_options.dataType == NexusDataType::PROTEIN) {
        oss << "PROTEIN MISSING=" << m_options.missingCharacter 
            << " GAP=" << m_options.gapCharacter;
    } else {
        oss << "MIXED";
    }

    oss << ";" << std::endl;

    oss << "  CHARLABELS" << std::endl;
    for (size_t i = 0; i < features.size(); ++i) {
        PhylogeneticFeatureExtractor extractor;
        std::string desc = extractor.getFeatureDescription(features[i]);
        oss << "    [" << (i + 1) << "] '" << features[i] << "' [" << desc << "]" << std::endl;
    }
    oss << "  ;" << std::endl;

    oss << "  MATRIX" << std::endl;

    for (const auto& ds : datasets) {
        std::string taxonName = escapeNexusString(truncateTaxonName(ds.taxonName));
        oss << "    " << taxonName;

        for (size_t i = 0; i < features.size(); ++i) {
            auto it = ds.featureMap.find(features[i]);
            double value = (it != ds.featureMap.end()) ? it->second : m_options.missingValue;

            if (m_options.discretizeContinuous || m_options.dataType == NexusDataType::STANDARD) {
                double minVal = getFeatureMin(datasets, features[i]);
                double maxVal = getFeatureMax(datasets, features[i]);
                oss << " " << formatDiscreteValue(value, minVal, maxVal);
            } else {
                oss << " " << formatContinuousValue(value);
            }
        }
        oss << std::endl;
    }

    oss << "  ;" << std::endl;
    oss << "END; [CHARACTERS]" << std::endl << std::endl;
    return oss.str();
}

std::string NexusExporter::generateContinuousBlock(const std::vector<PhylogeneticDataset>& datasets,
                                                     const std::vector<std::string>& selectedFeatures) {
    auto features = selectedFeatures.empty() ? getCommonFeatures(datasets) : selectedFeatures;

    std::ostringstream oss;
    oss << "BEGIN CONTINUOUS;" << std::endl;
    oss << "  DIMENSIONS NCHAR=" << features.size() << ";" << std::endl;
    oss << "  FORMAT MISSING=" << m_options.missingCharacter << ";" << std::endl;

    oss << "  CHARLABELS" << std::endl;
    for (size_t i = 0; i < features.size(); ++i) {
        PhylogeneticFeatureExtractor extractor;
        std::string desc = extractor.getFeatureDescription(features[i]);
        oss << "    '" << features[i] << "' [" << desc << "]" << std::endl;
    }
    oss << "  ;" << std::endl;

    oss << "  MATRIX" << std::endl;

    for (const auto& ds : datasets) {
        std::string taxonName = escapeNexusString(truncateTaxonName(ds.taxonName));
        oss << "    " << taxonName;

        for (size_t i = 0; i < features.size(); ++i) {
            auto it = ds.featureMap.find(features[i]);
            double value = (it != ds.featureMap.end()) ? it->second : m_options.missingValue;
            oss << " " << formatContinuousValue(value);
        }
        oss << std::endl;
    }

    oss << "  ;" << std::endl;
    oss << "END; [CONTINUOUS]" << std::endl << std::endl;
    return oss.str();
}

std::string NexusExporter::generateNotesBlock(const std::vector<PhylogeneticDataset>& datasets) {
    std::ostringstream oss;
    oss << "BEGIN NOTES;" << std::endl;
    oss << "  DIMENSIONS NTAX=" << datasets.size() << ";" << std::endl;
    oss << "  TEXT" << std::endl;

    for (const auto& ds : datasets) {
        std::string taxonName = escapeNexusString(truncateTaxonName(ds.taxonName));
        oss << "    TAXON=" << taxonName << std::endl;
        oss << "    Specimen ID: " << ds.specimenID << std::endl;
        oss << "    Centroid: (" << ds.centroid.x() << ", " 
            << ds.centroid.y() << ", " << ds.centroid.z() << ")" << std::endl;
        oss << "    Principal axis lengths: " 
            << ds.axisLengths.x() << ", " 
            << ds.axisLengths.y() << ", " 
            << ds.axisLengths.z() << std::endl;
        oss << "    Number of features: " << ds.features.size() << std::endl;

        oss << "    Features:" << std::endl;
        for (const auto& f : ds.features) {
            oss << "      " << f.name << ": " << f.value 
                << " " << f.unit << " [" << f.category << "]" << std::endl;
        }
        oss << std::endl;
    }

    oss << "  ;" << std::endl;
    oss << "END; [NOTES]" << std::endl << std::endl;
    return oss.str();
}

std::string NexusExporter::generateNexusString(const std::vector<PhylogeneticDataset>& datasets,
                                                const std::vector<std::string>& selectedFeatures) {
    if (datasets.empty()) {
        Logger::error("No datasets provided for Nexus export");
        return "";
    }

    std::ostringstream oss;

    if (m_options.includeHeaders) {
        oss << generateHeader(datasets);
    }

    oss << generateTaxaBlock(datasets);

    if (m_options.dataType == NexusDataType::CONTINUOUS) {
        oss << generateContinuousBlock(datasets, selectedFeatures);
    } else {
        oss << generateCharactersBlock(datasets, selectedFeatures);
    }

    if (m_options.includeNotes) {
        oss << generateNotesBlock(datasets);
    }

    return oss.str();
}

bool NexusExporter::fileExists(const std::string& filepath) {
    struct stat buffer;
    return (stat(filepath.c_str(), &buffer) == 0);
}

bool NexusExporter::createDirectory(const std::string& filepath) {
    std::filesystem::path path(filepath);
    std::filesystem::path dir = path.parent_path();
    if (!dir.empty() && !std::filesystem::exists(dir)) {
        return std::filesystem::create_directories(dir);
    }
    return true;
}

bool NexusExporter::exportToFile(const std::string& filepath,
                                  const std::vector<PhylogeneticDataset>& datasets,
                                  const std::vector<std::string>& selectedFeatures) {
    if (!createDirectory(filepath)) {
        Logger::error("Failed to create directory for Nexus export: " + filepath);
        return false;
    }

    std::string nexusContent = generateNexusString(datasets, selectedFeatures);
    if (nexusContent.empty()) {
        return false;
    }

    std::ofstream outFile(filepath);
    if (!outFile.is_open()) {
        Logger::error("Failed to open file for writing: " + filepath);
        return false;
    }

    outFile << nexusContent;
    outFile.close();

    Logger::info("Successfully exported Nexus file: " + filepath + 
                 " with " + std::to_string(datasets.size()) + " taxa and " +
                 std::to_string(getCommonFeatures(datasets).size()) + " characters");

    return true;
}

}
